### ISSUE TITLE
Froentend - Sing Up Log In Issue

### ISSUE THREAD

**Issue by codEno12** [CodingWithDan/Nothing-but-Notes#19] opened 2022-09-07 02:05 UTC
Bug where we cannot click on the text box on the sign up and log in. So no new users for us....
#
If you are already signed in the "sing up" button links to the user page but the log in button links to the log in page!

**Comment by ApplePieAngel** [comment] 2022-09-08 03:37
We've confirmed this was fixed last night over a call. And was due to missing files when pulling the repo. Do correct me if I'm wrong, but I'll be closing this issue for now.

**Closed as completed by ApplePieAngel** 2022-09-08 03:37 UTC
